name: CI

on:
  push:
    branches: [nix]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.system }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-26.04
            system: x86_64-linux
          - os: ubuntu-26.04-arm
            system: aarch64-linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Free disk space
        run: |
          df -h

          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          df -h

      - uses: actions/checkout@v7

      - uses: NixOS/nix-installer-action@main

      - name: Nix version
        run: nix --version

      - name: Run flake checks
        run: |
          nix flake check \
            --accept-flake-config \
            --print-build-logs \
            --show-trace

  build-gate:
    name: Build gate

    if: ${{ always() }}
    needs: [build]

    runs-on: ubuntu-24.04-arm

    steps:
      - name: Exit with error
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
